apiVersion: v1
kind: Service
metadata:
  name: {{ include "infocompass-backend.fullname" . }}
  labels:
    {{- include "infocompass-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api 
  selector:
    {{- include "infocompass-backend.selectorLabels" . | nindent 4 }}
